import OpenAI from 'openai';

let openai: OpenAI | null = null;

function getOpenAIClient(): OpenAI {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error('Missing OPENAI_API_KEY environment variable');
  }

  if (!openai) {
    openai = new OpenAI({
      apiKey,
    });
  }

  return openai;
}

/**
 * Prompts para diferentes estilos de narración
 */
const STYLE_PROMPTS = {
  documentary: `You are a legendary narrator like David Attenborough. 
Transform this transcription into a captivating documentary-style narration:
- Use a dramatic, authoritative, and profound tone
- Emphasize visual descriptions and emotional moments
- Use poetic language and metaphors
- Perfect for nature documentaries, travel videos, and dramatic content
- Maintain the original message but make it more cinematic and engaging`,

  educational: `You are a clear and patient teacher explaining concepts.
Transform this transcription into an educational narration:
- Use a friendly, clear, and explanatory tone
- Break down complex ideas into simple terms
- Use examples and analogies to clarify concepts
- Perfect for tutorials, how-to videos, and learning content
- Keep it accessible and easy to understand`,

  news: `You are a professional news anchor delivering a report.
Transform this transcription into a news-style narration:
- Use a neutral, professional, and objective tone
- Present facts clearly and concisely
- Maintain journalistic integrity
- Perfect for news reports, announcements, and formal content
- Stay balanced and informative`,

  storytelling: `You are an emotional storyteller captivating an audience.
Transform this transcription into a narrative story:
- Use an emotional, engaging, and expressive tone
- Build tension and emotional connections
- Use vivid imagery and sensory details
- Perfect for personal stories, experiences, and emotional content
- Make the audience feel invested in the story`,

  casual: `You are a friendly content creator talking to your audience.
Transform this transcription into a casual narration:
- Use a conversational, relaxed, and approachable tone
- Speak as if talking to a friend
- Use everyday language and expressions
- Perfect for vlogs, casual videos, and personal content
- Keep it authentic and relatable`,

  professional: `You are a serious corporate presenter delivering a message.
Transform this transcription into a professional narration:
- Use a formal, reliable, and authoritative tone
- Maintain corporate professionalism
- Focus on credibility and expertise
- Perfect for business presentations, corporate videos, and formal content
- Keep it polished and trustworthy`,
};

/**
 * Language-specific instructions for translation
 */
const LANGUAGE_INSTRUCTIONS = {
  es: 'Translate to natural Spanish (Español latinoamericano neutro)',
  en: 'Translate to natural English (neutral accent)',
  pt: 'Translate to natural Portuguese (Português brasileiro)',
  fr: 'Translate to natural French (Français standard)',
  de: 'Translate to natural German (Deutsch)',
  it: 'Translate to natural Italian (Italiano)',
  ja: 'Translate to natural Japanese (日本語)',
  zh: 'Translate to natural Chinese (简体中文)',
};

/**
 * Genera un script de narración traducido y estilizado usando GPT-4
 * @param transcription - Transcripción original del video
 * @param targetLanguage - Idioma objetivo (es, en, pt, fr, de, it, ja, zh)
 * @param style - Estilo de narración (documentary, educational, news, storytelling, casual, professional)
 * @returns Script traducido y estilizado listo para ElevenLabs
 */
export async function generateNarrationScript(
  transcription: string,
  targetLanguage: string,
  style: string
): Promise<string> {
  const stylePrompt =
    STYLE_PROMPTS[style as keyof typeof STYLE_PROMPTS] ||
    STYLE_PROMPTS.documentary;
  const languageInstruction =
    LANGUAGE_INSTRUCTIONS[
      targetLanguage as keyof typeof LANGUAGE_INSTRUCTIONS
    ] || LANGUAGE_INSTRUCTIONS.en;

  const systemPrompt = `${stylePrompt}

${languageInstruction}

Important guidelines:
- Maintain the core message and facts from the original transcription
- Adapt the tone and style according to the narration style
- Make it natural and suitable for voice narration
- Keep it concise and engaging for video format
- Return ONLY the translated narration script, no explanations`;

  try {
    const client = getOpenAIClient();

    const response = await client.chat.completions.create({
      model: 'gpt-4',
      messages: [
        { role: 'system', content: systemPrompt },
        {
          role: 'user',
          content: `Original transcription:\n\n${transcription}`,
        },
      ],
      temperature: 0.7,
      max_tokens: 1000,
    });

    const script = response.choices[0]?.message?.content?.trim();

    if (!script) {
      throw new Error('No script generated by GPT-4');
    }

    return script;
  } catch (error) {
    console.error('Error generating narration script:', error);
    throw new Error(
      `Failed to generate narration script: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}
